### ISSUE TITLE
Intltool is in shared-modules

### ISSUE THREAD

**Issue by bochecha** [flathub/com.github.junrrein.PDFSlicer#29]
Ideally intltool should be dropped entirely by all upstreams currently using it as it's been deprecated for some time now in favour of plain gettext, but that's not always something we can do here at Flathub.

However, you could move to using intltool from shared-modules: https://github.com/flathub/shared-modules/tree/master/intltool

I'm happy to send a pull request if you need help with that. :slightly_smiling_face:

**Comment by junrrein** [comment]
Hi there, sorry for the sooo late response.

I didn't know intltool was deprecated, so thanks for letting me know! I'm tracking that at https://github.com/junrrein/pdfslicer/issues/161.

Anyway, for anyone reading this: I was using intltool from outside of shared-modules, since I wanted the non-Flathub Flatpak build to work using the same manifest. But I understand if folks at Flathub thinks it's a bad idea.
